[formatter.nix]
command = "bash"
options = [
    "-eucx",
    """
    find . -type f \
    | grep -e ".nix$" \
    | xargs nixpkgs-fmt
    """,
]
includes = [ "./**/*.nix" ]

[formatter.shellscript]
command = "shfmt"
includes = [ "./**/*.sh" ]

[formatter.yaml]
command = "yamlfmt"
includes = [ "./**/*.yaml", "./**/*.yml" ]
