[formatter.nix]
command = "nixpkgs-fmt"
includes = ["./**/*.nix"]

[formatter.shellscript]
command = "shfmt"
includes = ["./**/*.sh"]

# TODO: doesn't work with yamlfmt because https://github.com/numtide/treefmt/issues/279
# [formatter.yaml]
# command = "yamlfmt"
# includes = ["./**/*.yaml", "./**/*.yml"]

[formatter.dprint]
command = "dprint"
options = ["fmt"]
includes = ["./**/*.json", "./**/*.md", "./**/*.toml"]
