name: build-macos

on:
  # TODO: unable to build in x86_64-darwin
  workflow_dispatch:

jobs:
  build-darwin:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Build
        run: make apply/darwin
