name: update

on:
  schedule:
    # 毎月25日の00:00に実行
    - cron: '0 0 25 * *'
  workflow_dispatch:

jobs:
  update-flake-lock:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Update flake.lock"
          pr-labels: |
            dependencies
